[package]
name = "wizzard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.12.0"
polars = "0.30.0"
tokio = {version ="1.12.0", features = ["full"] }
rand = "0.8.4"


